### ISSUE TITLE
cannot CordovaHtmlOutputPlugin

### ISSUE THREAD

**Issue by poptong** [kevinqqnj/cordova-template-framework7-vue-v2#1]
Error: Cannot find module './webpack/plugins/CordovaHtmlOutputPlugin.js'

**Comment by kevinqqnj** [comment]
thanks for reminding! 
The '/webpack/plugins/CordovaHtmlOutputPlugin.js' was excluded by .gitignore file.
Now it's fixed, pls re-clone the repo.
